# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

# 1 Set price tier to 0, indicating it*s a free app.
price_tier(0)

# 2 Answer the questions Apple would present to you upon manually submitting for review.
submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})

# 3 Provide the app rating configuration location.
app_rating_config_path("./fastlane/metadata/app_store_rating_config.json")

# 4 Provide the .ipa file location.
ipa("./fastlane/builds/DiggHeartPower.ipa")

# 5 Set submit_for_review to true to automatically submit the app for review.
submit_for_review(true)

# 6 Set automatic_release to false so you*ll have to release the app manually
# after it's accepted by app review.
automatic_release(false)

# to make the lane completely hands-free
# This causes fastlane to skip screenshot and metadata approval.

force(true)
