# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 11 Pro Max",
#   "iPhone 8",
   "iPhone 8 Plus"
#   "iPhone SE",
#   "iPhone X",
#   "iPad Pro (12.9-inch)",
#   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p",
#   "Apple Watch Series 6 - 44mm"
 ])

# 2 - A list of supported languages

languages([
  'en-US'
])

# The name of the scheme which contains the UI Tests
scheme("DiggHeartPower Snapshot UITests")

# Where should the resulting screenshots be stored?
#output_directory("./screenshots")
output_directory "./fastlane/screenshots"

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
